config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :destroy, :edit, :update]
  def index
    @article = Article.all
  end

  def show; end

  def edit; end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(article) do |form| %>
  <%= form.input :title, placeholder: 'Title here' %>
  <%= form.input :content, placeholder: 'Some content here' %>
  <%= form.submit action_name == 'new' ? 'save task' : 'edit task' %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>All articles</h1>
<% @article.each do |article| %>
  <h2><%= link_to article.title, article_path(article) %></h2>
  <%= article.content %>
<% end %>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h2>
  <%= @article.title %>
</h2>
  <hr>
  <%= @article.content %>
  <hr>
  <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_article_path %>
  <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe,
              article_path(@article),
              method: :delete,
              data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>